name: beatu-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.115.0
    - uvicorn==0.30.0
    - pydantic==1.10.15
    - sqlalchemy==2.0.36
    - redis==5.0.8
    - python-dotenv==1.0.1
    - pytest==8.3.3
    - pymysql==1.1.1

